{% set name = "rollbar" %}
{% set version = "0.15.2" %}
{% set sha256 = "5e80fe7c9b15e84f5b72e45ebaa85bba1c13234e447a5f3801d094eb379c2d0e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - rollbar=rollbar.cli:main

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - requests >=0.12.1
    - six >=1.9.0

test:
  requires:
    - pip
  imports:
    - rollbar
  commands:
    - pip check

about:
  home: https://github.com/rollbar/pyrollbar
  license: MIT
  license_family: MIT
  summary: Rollbar notifier for Python

  description: |
    Python notifier for reporting exceptions, errors, and log messages to Rollbar.
  doc_url: https://rollbar.com/docs/notifier/pyrollbar/

extra:
  recipe-maintainers:
    - TheOriginalAlex
