{% set name = "rollbar" %}
{% set version = "1.0.0" %}
{% set sha256 = "6347b7e49f22f0296fc287a6aea75d642cf64494d2ee127042a7a593c97df3af" %}
{% set python_min = "3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - rollbar=rollbar.cli:main

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - pip
  run:
    - python >={{ python_min }}
    - requests >=0.12.1

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - rollbar
  commands:
    - pip check
    - rollbar --help

about:
  home: https://github.com/rollbar/pyrollbar
  license: MIT
  license_file: LICENSE
  summary: Rollbar notifier for Python
  description: Easy and powerful exception tracking with Rollbar. Send messages and exceptions with arbitrary context, get back aggregates, and debug production issues quickly.
  doc_url: https://rollbar.com/docs/notifier/pyrollbar/

extra:
  recipe-maintainers:
    - fpaniagua
    - TheOriginalAlex
